In [1]:
from statsbombpy import sb

In [2]:
# show all competitions
sb.competitions()

# show unique competitions
sb.competitions().drop_duplicates(['country_name', 'competition_name'])

e:\manu\ana\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,16,4,Europe,Champions League,male,False,False,2018/2019,2022-08-14T16:57:15.866765,2021-06-13T16:17:31.694,None,2022-08-14T16:57:15.866765
15,37,90,England,FA Women's Super League,female,False,False,2020/2021,2022-08-16T02:10:37.220648,2021-06-13T16:17:31.694,None,2022-08-16T02:10:37.220648
18,43,3,International,FIFA World Cup,male,False,True,2018,2022-09-05T17:17:56.670896,2021-06-13T16:17:31.694,None,2022-09-05T17:17:56.670896
19,1238,108,India,Indian Super league,male,False,False,2021/2022,2022-06-08T12:40:59.857067,None,None,2022-06-08T12:40:59.857067
20,11,90,Spain,La Liga,male,False,False,2020/2021,2022-02-11T14:56:09.076,2022-08-16T21:50:36.812060,2022-08-16T21:50:36.812060,2022-02-11T14:56:09.076
37,49,3,United States of America,NWSL,female,False,False,2018,2021-11-06T05:53:29.435016,2021-06-13T16:17:31.694,None,2021-11-06T05:53:29.435016
38,2,44,England,Premier League,male,False,False,2003/2004,2021-11-14T22:29:00.646120,2021-06-13T16:17:31.694,None,2021-11-14T22:29:00.646120
39,55,43,Europe,UEFA Euro,male,False,True,2020,2022-02-01T17:20:34.319496,2022-08-04T12:00,2022-08-04T12:00,2022-02-01T17:20:34.319496
40,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2022-08-01T07:46:11.595364,2022-09-13T17:04:11.418708,2022-09-13T17:04:11.418708,2022-08-01T07:46:11.595364
41,72,30,International,Women's World Cup,female,False,True,2019,2022-07-13T20:21:27.033445,2021-06-13T16:17:31.694,None,2022-07-13T20:21:27.033445

In [5]:
pl = sb.matches(competition_id=2, season_id=44)

e:\manu\ana\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [6]:
pl.head(5)

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated,last_updated_360,match_week,competition_stage,stadium,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3749052,2004-02-07,16:00:00.000,England - Premier League,2003/2004,Wolverhampton Wanderers,Arsenal,1,3,available,...,2020-07-29T05:00,2021-06-13T16:17:31.694,2,Regular Season,Molineux Stadium,Dave Jones,Arsène Wenger,1.1.0,2,2
1,3749522,2003-12-26,13:00:00.000,England - Premier League,2003/2004,Arsenal,Wolverhampton Wanderers,3,0,available,...,2020-07-29T05:00,2021-06-13T16:17:31.694,18,Regular Season,Highbury Stadium,Arsène Wenger,Dave Jones,1.1.0,2,2
2,3749246,2004-03-28,17:05:00.000,England - Premier League,2003/2004,Arsenal,Manchester United,1,1,available,...,2020-07-29T05:00,2021-06-13T16:17:31.694,30,Regular Season,Highbury Stadium,Arsène Wenger,Alex Ferguson,1.1.0,2,2
3,3749257,2004-05-15,16:00:00.000,England - Premier League,2003/2004,Arsenal,Leicester City,2,1,available,...,2020-08-30T08:12:14.579037,2021-06-13T16:17:31.694,38,Regular Season,Highbury Stadium,Arsène Wenger,Micky Adams,1.1.0,2,2
4,3749642,2004-02-28,16:00:00.000,England - Premier League,2003/2004,Arsenal,Charlton Athletic,2,1,available,...,2020-07-29T05:00,2021-06-13T16:17:31.694,27,Regular Season,Highbury Stadium,Arsène Wenger,Alan Curbishley,1.1.0,2,2

In [7]:
mat_id = 3749246
pl[pl['match_id']==mat_id]

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated,last_updated_360,match_week,competition_stage,stadium,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
2,3749246,2004-03-28,17:05:00.000,England - Premier League,2003/2004,Arsenal,Manchester United,1,1,available,...,2020-07-29T05:00,2021-06-13T16:17:31.694,30,Regular Season,Highbury Stadium,Arsène Wenger,Alex Ferguson,1.1.0,2,2

In [8]:
lineups = sb.lineups(match_id=mat_id)

e:\manu\ana\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [9]:
lineups['Arsenal']

,player_id,player_name,player_nickname,jersey_number,country,cards,positions
0,15042,Dennis Bergkamp,None,10,Netherlands,[],"[{'position_id': 16, 'position': 'Left Midfiel..."
1,15515,Patrick Vieira,None,4,France,[],"[{'position_id': 9, 'position': 'Right Defensi..."
2,15516,Thierry Henry,None,14,France,[],"[{'position_id': 24, 'position': 'Left Center ..."
3,15637,"Sulzeer Jeremiah ""Sol"" Campbell",Sol Campbell,23,England,[],"[{'position_id': 5, 'position': 'Left Center B..."
4,15754,Fredrik Ljungberg,None,8,Sweden,[],"[{'position_id': 12, 'position': 'Right Midfie..."
5,19312,Robert Pirès,None,7,France,[],"[{'position_id': 16, 'position': 'Left Midfiel..."
6,20015,Jens Lehmann,None,1,Germany,[],"[{'position_id': 1, 'position': 'Goalkeeper', ..."
7,20302,Gaël Clichy,None,22,France,"[{'time': '73:14', 'card_type': 'Yellow Card',...","[{'position_id': 6, 'position': 'Left Back', '..."
8,23816,José Antonio Reyes Calderón,José Antonio Reyes,9,Spain,[],"[{'position_id': 22, 'position': 'Right Center..."
9,24971,Nwankwo Christian Kanu,None,25,Nigeria,[],[]
10,26014,Eduardo César Daude Gaspar,Edu Gaspar,17,Brazil,[],"[{'position_id': 11, 'position': 'Left Defensi..."
11,26194,Pascal Cygan,None,18,France,[],"[{'position_id': 12, 'position': 'Right Midfie..."
12,38412,Kolo Habib Touré,Kolo Touré,28,Côte d'Ivoire,[],"[{'position_id': 3, 'position': 'Right Center ..."
13,40221,Gilberto Aparecido da Silva,Gilberto Silva,19,Brazil,[],"[{'position_id': 22, 'position': 'Right Center..."
14,40222,Laureano Bisan-Etame Mayer,Lauren,12,Cameroon,[],"[{'position_id': 2, 'position': 'Right Back', ..."
15,42458,Graham Stack,None,33,Ireland,[],[]

In [10]:
lineups['Manchester United']

,player_id,player_name,player_nickname,jersey_number,country,cards,positions
0,4022,Darren Fletcher,None,24,Scotland,[],"[{'position_id': 12, 'position': 'Right Midfie..."
1,13042,Tim Howard,None,14,United States of America,[],[]
2,15402,Gary Neville,None,2,England,[],"[{'position_id': 2, 'position': 'Right Back', ..."
3,15590,Ole Gunnar Solskjær,Ole Gunnar Solskjaer,20,Norway,[],"[{'position_id': 12, 'position': 'Right Midfie..."
4,15660,Phil Neville,None,3,England,[],[]
5,15666,Paul Scholes,None,18,England,"[{'time': '24:38', 'card_type': 'Yellow Card',...","[{'position_id': 19, 'position': 'Center Attac..."
6,16890,"John O""Shea",John O'Shea,22,Ireland,[],"[{'position_id': 6, 'position': 'Left Back', '..."
7,19729,Ruud van Nistelrooy,Ruud van Nistelrooy,10,Netherlands,[],"[{'position_id': 23, 'position': 'Center Forwa..."
8,20175,Ryan Giggs,None,11,Wales,[],"[{'position_id': 16, 'position': 'Left Midfiel..."
9,20341,Mikaël Silvestre,None,27,France,[],"[{'position_id': 5, 'position': 'Left Center B..."
10,20505,Louis Saha,None,9,France,[],"[{'position_id': 13, 'position': 'Right Center..."
11,24761,Nicky Butt,None,8,England,[],[]
12,24805,Roy Keane,None,16,Ireland,[],"[{'position_id': 15, 'position': 'Left Center ..."
13,40364,Roy Carroll,None,13,Northern Ireland,[],"[{'position_id': 1, 'position': 'Goalkeeper', ..."
14,40365,Eric Daniel Djemba-Djemba,None,19,Cameroon,[],"[{'position_id': 13, 'position': 'Right Center..."
15,40366,Wes Brown,None,6,England,[],"[{'position_id': 3, 'position': 'Right Center ..."

In [11]:
df_events = sb.events(match_id=mat_id)

e:\manu\ana\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [12]:
df_events.columns

Index(['50_50', 'ball_receipt_outcome', 'ball_recovery_recovery_failure',
       'block_offensive', 'carry_end_location', 'clearance_aerial_won',
       'clearance_body_part', 'clearance_head', 'clearance_left_foot',
       'clearance_right_foot', 'counterpress', 'dribble_outcome',
       'dribble_overrun', 'duel_outcome', 'duel_type', 'duration',
       'foul_committed_advantage', 'foul_committed_card', 'foul_won_advantage',
       'foul_won_defensive', 'goalkeeper_body_part', 'goalkeeper_end_location',
       'goalkeeper_outcome', 'goalkeeper_position', 'goalkeeper_punched_out',
       'goalkeeper_success_in_play', 'goalkeeper_technique', 'goalkeeper_type',
       'id', 'index', 'interception_outcome', 'location', 'match_id', 'minute',
       'miscontrol_aerial_won', 'off_camera', 'out', 'pass_aerial_won',
       'pass_angle', 'pass_assisted_shot_id', 'pass_body_part', 'pass_cross',
       'pass_cut_back', 'pass_deflected', 'pass_end_location',
       'pass_goal_assist', 'pass_height', 'pass_inswinging', 'pass_length',
       'pass_no_touch', 'pass_outcome', 'pass_outswinging', 'pass_recipient',
       'pass_shot_assist', 'pass_straight', 'pass_switch', 'pass_technique',
       'pass_through_ball', 'pass_type', 'period', 'play_pattern', 'player',
       'player_id', 'position', 'possession', 'possession_team',
       'possession_team_id', 'related_events', 'second', 'shot_aerial_won',
       'shot_body_part', 'shot_end_location', 'shot_first_time',
       'shot_freeze_frame', 'shot_key_pass_id', 'shot_one_on_one',
       'shot_outcome', 'shot_statsbomb_xg', 'shot_technique', 'shot_type',
       'substitution_outcome', 'substitution_replacement', 'tactics', 'team',
       'timestamp', 'type', 'under_pressure'],
      dtype='object')

In [13]:
df_events = df_events[['timestamp','team', 'type', 'minute', 'location', 'pass_end_location', 'player']]
df_events = df_events.sort_values(['minute', 'timestamp'])

In [14]:
df_events.tail(30)

,timestamp,team,type,minute,location,pass_end_location,player
2129,00:47:32.520,Manchester United,Carry,92,"[23.1, 25.1]",NaN,Louis Saha
2583,00:47:32.520,Manchester United,Ball Recovery,92,"[23.1, 25.1]",NaN,Louis Saha
2458,00:47:33.020,Arsenal,Pressure,92,"[105.3, 54.5]",NaN,Gilberto Aparecido da Silva
2771,00:47:34.227,Manchester United,Dispossessed,92,"[21.1, 26.9]",NaN,Louis Saha
2868,00:47:34.227,Arsenal,Duel,92,"[99.0, 53.2]",NaN,Gilberto Aparecido da Silva
829,00:47:35.075,Manchester United,Pass,92,"[16.7, 28.4]","[42.9, 27.5]",Mikaël Silvestre
2584,00:47:36.192,Arsenal,Ball Recovery,92,"[77.2, 52.6]",NaN,Patrick Vieira
2130,00:47:38.596,Arsenal,Carry,92,"[61.7, 44.0]",NaN,Kolo Habib Touré
2585,00:47:38.596,Arsenal,Ball Recovery,92,"[61.7, 44.0]",NaN,Kolo Habib Touré
2459,00:47:39.326,Manchester United,Pressure,92,"[56.4, 40.2]",NaN,Ruud van Nistelrooy
830,00:47:42.100,Arsenal,Pass,92,"[83.3, 52.6]","[86.6, 73.6]",Kolo Habib Touré
1532,00:47:43.297,Arsenal,Ball Receipt*,92,"[86.6, 73.6]",NaN,Gilberto Aparecido da Silva
2131,00:47:43.297,Arsenal,Carry,92,"[86.6, 73.6]",NaN,Gilberto Aparecido da Silva
831,00:47:44.613,Arsenal,Pass,92,"[87.2, 73.0]","[112.0, 63.6]",Gilberto Aparecido da Silva
1533,00:47:45.194,Arsenal,Ball Receipt*,92,"[112.0, 63.6]",NaN,Thierry Henry
2132,00:47:45.194,Arsenal,Carry,92,"[112.0, 63.6]",NaN,Thierry Henry
2993,00:47:45.194,Manchester United,Clearance,92,"[15.5, 8.8]",NaN,"John O""Shea"
2460,00:47:46.111,Manchester United,Pressure,92,"[5.7, 19.5]",NaN,Mikaël Silvestre
2772,00:47:46.735,Arsenal,Dispossessed,92,"[115.3, 65.3]",NaN,Thierry Henry
2869,00:47:46.735,Manchester United,Duel,92,"[4.8, 14.8]",NaN,Mikaël Silvestre
2133,00:47:48.072,Arsenal,Carry,92,"[115.9, 70.7]",NaN,Thierry Henry
2586,00:47:48.072,Arsenal,Ball Recovery,92,"[115.9, 70.7]",NaN,Thierry Henry
832,00:47:49.282,Arsenal,Pass,92,"[116.7, 70.7]","[113.0, 50.0]",Thierry Henry
2134,00:47:50.037,Manchester United,Carry,92,"[7.1, 30.1]",NaN,Roy Keane
2587,00:47:50.037,Manchester United,Ball Recovery,92,"[7.1, 30.1]",NaN,Roy Keane
833,00:47:51.208,Manchester United,Pass,92,"[4.8, 28.6]","[3.0, 18.6]",Roy Keane
834,00:47:52.661,Manchester United,Pass,92,"[3.0, 18.6]","[43.2, 26.9]",Mikaël Silvestre
1534,00:47:52.661,Manchester United,Ball Receipt*,92,"[3.0, 18.6]",NaN,Mikaël Silvestre
3088,00:47:55.693,Arsenal,Half End,92,NaN,NaN,NaN
3089,00:47:55.693,Manchester United,Half End,92,NaN,NaN,NaN